export let role = "admin";

export const paraPenyuluhData = [
  {
    id: "P001",
    username: "john_doe",
    name: "John Doe",
    email: "john@doe.com",
    phone: "081234567890",
    address: "Jl. Raya No.1",
    img: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg",
    bidang: ["Jagung", "Padi"],
    desaBinaan: [
      {
        name: "Jatingarang",
        kelompokTani: [
          {
            name: "Kelompok Tani Gemar",
            ketua: "Bpk Surojo",
            email: "kt1@desa.com",
            phone: "0811111111",
            address: "RT 01 RW 01",
            img: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg",
          },
        ],
      },
      {
        name: "Kwasen",
        kelompokTani: [
          {
            name: "Kelompok Tani Kwasen 1",
            ketua: "Bpk A",
            email: "ktA@desa.com",
            phone: "0811111122",
            address: "RT 02 RW 01",
            img: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg",
          },
        ],
      },
    ],
  },
  {
    id: "P002",
    username: "lukman",
    name: "Lukman",
    email: "lukman@doe.com",
    phone: "081234567891",
    address: "Jl. Raya No.2",
    img: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg",
    bidang: ["Padi", "Sayuran"],
    desaBinaan: [
      {
        name: "Longkeyang",
        kelompokTani: [
          {
            name: "Kelompok Tani Longkeyang",
            ketua: "Bpk Budi",
            email: "kt2@desa.com",
            phone: "0812222222",
            address: "RT 03 RW 01",
            img: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg",
          },
        ],
      },
      {
        name: "Gunungbatu",
        kelompokTani: [
          {
            name: "Kelompok Tani Gunung",
            ketua: "Bpk Eko",
            email: "kt3@desa.com",
            phone: "0813333333",
            address: "RT 04 RW 01",
            img: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg",
          },
        ],
      },
    ],
  },
  {
    id: "P003",
    username: "rahayu",
    name: "Rahayu",
    email: "rahayu@doe.com",
    phone: "081234567892",
    address: "Jl. Raya No.3",
    img: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg",
    bidang: ["Jagung", "Tebu"],
    desaBinaan: [
      {
        name: "Kebandaran",
        kelompokTani: [
          {
            name: "Kelompok Tani Kebandaran",
            ketua: "Bpk Andi",
            email: "kt4@desa.com",
            phone: "0814444444",
            address: "RT 05 RW 01",
            img: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg",
          },
        ],
      },
    ],
  },
  {
    id: "P004",
    username: "abadi",
    name: "Abadi",
    email: "abadi@doe.com",
    phone: "081234567893",
    address: "Jl. Raya No.4",
    img: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg",
    bidang: ["Terong", "Ubi"],
    desaBinaan: [
      {
        name: "Pendowo",
        kelompokTani: [
          {
            name: "Kelompok Tani Pendowo",
            ketua: "Bpk Fajar",
            email: "kt5@desa.com",
            phone: "0815555555",
            address: "RT 06 RW 01",
            img: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg",
          },
        ],
      },
    ],
  },
  {
    id: "P005",
    username: "igit",
    name: "Igit",
    email: "igit@doe.com",
    phone: "081234567894",
    address: "Jl. Raya No.5",
    img: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg",
    bidang: ["Jati", "Sorgum"],
    desaBinaan: [
      {
        name: "Jatiroyom",
        kelompokTani: [
          {
            name: "Kelompok Tani Jati",
            ketua: "Bpk Hadi",
            email: "kt6@desa.com",
            phone: "0816666666",
            address: "RT 07 RW 01",
            img: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg",
          },
        ],
      },
    ],
  },
  {
    id: "P006",
    username: "santika",
    name: "Santika",
    email: "santika@doe.com",
    phone: "081234567895",
    address: "Jl. Raya No.6",
    img: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg",
    bidang: ["Sayuran", "Padi"],
    desaBinaan: [
      {
        name: "Sukasari",
        kelompokTani: [
          {
            name: "Kelompok Tani Sukasari",
            ketua: "Bpk Danu",
            email: "kt7@desa.com",
            phone: "0817777777",
            address: "RT 08 RW 01",
            img: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg",
          },
        ],
      },
    ],
  },
  {
    id: "P007",
    username: "bayu",
    name: "Bayu Saputra",
    email: "bayu@doe.com",
    phone: "081234567896",
    address: "Jl. Raya No.7",
    img: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg",
    bidang: ["Jagung", "Kedelai"],
    desaBinaan: [
      {
        name: "Mekarsari",
        kelompokTani: [
          {
            name: "Kelompok Tani Mekarsari",
            ketua: "Bpk Rudi",
            email: "kt8@desa.com",
            phone: "0818888888",
            address: "RT 09 RW 01",
            img: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg",
          },
        ],
      },
    ],
  },
  {
    id: "P008",
    username: "lilis",
    name: "Lilis Wulandari",
    email: "lilis@doe.com",
    phone: "081234567897",
    address: "Jl. Raya No.8",
    img: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg",
    bidang: ["Teh", "Tebu"],
    desaBinaan: [
      {
        name: "Sukamaju",
        kelompokTani: [
          {
            name: "Kelompok Tani Sukamaju",
            ketua: "Bpk Surya",
            email: "kt9@desa.com",
            phone: "0819999999",
            address: "RT 10 RW 01",
            img: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg",
          },
        ],
      },
    ],
  },
  {
    id: "P009",
    username: "fikri",
    name: "Fikri Ramadhan",
    email: "fikri@doe.com",
    phone: "081234567898",
    address: "Jl. Raya No.9",
    img: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg",
    bidang: ["Kopi", "Cengkeh"],
    desaBinaan: [
      {
        name: "Cibodas",
        kelompokTani: [
          {
            name: "Kelompok Tani Cibodas",
            ketua: "Bpk Toni",
            email: "kt10@desa.com",
            phone: "0810000000",
            address: "RT 11 RW 01",
            img: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg",
          },
        ],
      },
    ],
  },
  {
    id: "P010",
    username: "mega",
    name: "Mega Sari",
    email: "mega@doe.com",
    phone: "081234567899",
    address: "Jl. Raya No.10",
    img: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg",
    bidang: ["Padi", "Jagung", "Ubi"],
    desaBinaan: [
      {
        name: "Margasari",
        kelompokTani: [
          {
            name: "Kelompok Tani Margasari",
            ketua: "Bpk Yanto",
            email: "kt11@desa.com",
            phone: "0811110000",
            address: "RT 12 RW 01",
            img: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg",
          },
        ],
      },
    ],
  },
];

export const paraKelompokTaniData = [
     {
    id: 1,
    kelompokTaniId: "KT001",
    name: "Kelompok Tani Gemar",
    ketua: "Bpk Surojo",
    email: "kt1@desa.com",
    phone: "0811111111",
    address: "RT 01 RW 01",
    photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    desa: "Jatingarang",
    penyuluhId: "P001",
  },
  {
    id: 2,
    kelompokTaniId: "KT002",
    name: "Kelompok Tani Kwasen 1",
    ketua: "Bpk A",
    email: "ktA@desa.com",
    phone: "0811111122",
    address: "RT 02 RW 01",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg",
    desa: "Kwasen",
    penyuluhId: "P001",
  },
  {
    id: 3,
    kelompokTaniId: "KT003",
    name: "Kelompok Tani Longkeyang",
    ketua: "Bpk Budi",
    email: "kt2@desa.com",
    phone: "0812222222",
    address: "RT 03 RW 01",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg",
    desa: "Longkeyang",
    penyuluhId: "P002",
  },
  {
    id: 4,
    kelompokTaniId: "KT004",
    name: "Kelompok Tani Gunung",
    ketua: "Bpk Eko",
    email: "kt3@desa.com",
    phone: "0813333333",
    address: "RT 04 RW 01",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg",
    desa: "Gunungbatu",
    penyuluhId: "P002",
  },
  {
    id: 5,
    kelompokTaniId: "KT005",
    name: "Kelompok Tani Kebandaran",
    ketua: "Bpk Andi",
    email: "kt4@desa.com",
    phone: "0814444444",
    address: "RT 05 RW 01",
    photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg",
    desa: "Kebandaran",
    penyuluhId: "P003",
  },
  {
    id: 6,
    kelompokTaniId: "KT006",
    name: "Kelompok Tani Pendowo",
    ketua: "Bpk Fajar",
    email: "kt5@desa.com",
    phone: "0815555555",
    address: "RT 06 RW 01",
    photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg",
    desa: "Pendowo",
    penyuluhId: "P004",
  },
  {
    id: 7,
    kelompokTaniId: "KT007",
    name: "Kelompok Tani Jati",
    ketua: "Bpk Hadi",
    email: "kt6@desa.com",
    phone: "0816666666",
    address: "RT 07 RW 01",
    photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg",
    desa: "Jatiroyom",
    penyuluhId: "P005",
  },
  {
    id: 8,
    kelompokTaniId: "KT008",
    name: "Kelompok Tani Sukasari",
    ketua: "Bpk Danu",
    email: "kt7@desa.com",
    phone: "0817777777",
    address: "RT 08 RW 01",
    photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg",
    desa: "Sukasari",
    penyuluhId: "P006",
  },
  {
    id: 9,
    kelompokTaniId: "KT009",
    name: "Kelompok Tani Mekarsari",
    ketua: "Bpk Rudi",
    email: "kt8@desa.com",
    phone: "0818888888",
    address: "RT 09 RW 01",
    photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg",
    desa: "Mekarsari",
    penyuluhId: "P007",
  },
  {
    id: 10,
    kelompokTaniId: "KT010",
    name: "Kelompok Tani Sukamaju",
    ketua: "Bpk Surya",
    email: "kt9@desa.com",
    phone: "0819999999",
    address: "RT 10 RW 01",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg",
    desa: "Sukamaju",
    penyuluhId: "P008",
  },
];

export const paraKiosPertanianData = [
  {
    id: 1,
    name: "Toko Tanimaju",
    pemilik: "Bpk Surojo",
    phone: "1234567890",
    parakelompoktani: ["Kelompok Tani Gemar","..."],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Toko Joss",
    pemilik: "Bpk Budi",
    phone: "1234567890",
    parakelompoktani: ["Kelompok Tani Sukamaju", "..."],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Toko Lancar",
    pemilik: "Bpk Firman",
    phone: "1234567890",
    parakelompoktani: ["Kelompok Tani Oke", "..."],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Toko Bagus",
    pemilik: "Bpk hafezs",
    phone: "1234567890",
    parakelompoktani: ["Kelompok Tani Bersama", "..."],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Toko Apik",
    pemilik: "Bpk Agasta",
    phone: "1234567890",
    parakelompoktani: ["Kelompok Tani Lestari", "..."],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Toko Kembang",
    pemilik: "Bpk Revan",
    phone: "1234567890",
    parakelompoktani: ["Kelompok Tani Gas", "..."],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Toko Taniku",
    pemilik: "Bpk Hilmi",
    phone: "1234567890",
    parakelompoktani: ["Kelompok Tani Maju", "..."],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Toko Tuku",
    pemilik: "Bpk Fajar",
    phone: "1234567890",
    parakelompoktani: ["Kelompok Tani Kembang", "..."],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Toko Suka",
    pemilik: "Bpk Bima",
    phone: "1234567890",
    parakelompoktani: ["Kelompok Tani Lestari", "..."],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "Toko Bersama",
    pemilik: "Bpk Reksa",
    phone: "1234567890",
    parakelompoktani: ["Kelompok Tani Gembur", "..."],
    address: "123 Main St, Anytown, USA",
  },
];

export const kumpulanMateriData = [
{
    id: 1,
    topik: "Penyuluhan Terasiring",
    fileName: "Penyuluhan Terasiring",
    fileUrl: "/files/terasiring.pdf",
    uploadDate: "2025-01-04",
    updateDate: "2025-01-04",
    penyuluh: "Olivia Rhye",
},
{
    id: 2,
    topik: "Penyuluhan Cabai",
    fileName: "Penyuluhan Cabai",
    fileUrl: "/files/cabai.pdf",
    uploadDate: "2025-01-04",
    updateDate: "2025-01-04",
    penyuluh: "Tommy Wise",
},
{
    id: 3,
    topik: "Penyuluhan Tomat",
    fileName: "Penyuluhan Tomat",
    fileUrl: "/files/tomat.pdf",
    uploadDate: "2025-01-04",
    updateDate: "2025-01-04",
    penyuluh: "Joseph Padilla",
},
{
    id: 4,
    topik: "Penyuluhan Padi",
    fileName: "Penyuluhan Padi",
    fileUrl: "/files/padi.pdf",
    uploadDate: "2025-01-04",
    updateDate: "2025-01-04",
    penyuluh: "Blake Joseph",
},
{
    id: 5,
    topik: "Penyuluhan Jagung",
    fileName: "Penyuluhan Jagung",
    fileUrl: "/files/jagung.pdf",
    uploadDate: "2025-01-04",
    updateDate: "2025-01-04",
    penyuluh: "Tom Bennett",
},
{
    id: 6,
    topik: "Penyuluhan Irigasi",
    fileName: "Penyuluhan Irigasi",
    fileUrl: "/files/irigasi.pdf",
    uploadDate: "2025-01-04",
    updateDate: "2025-01-04",
    penyuluh: "Aaron Collins",
},
{
    id: 7,
    topik: "Penyuluhan Alat Bantu Tani",
    fileName: "Penyuluhan Alat Bantu Tani",
    fileUrl: "/files/alatbantu.pdf",
    uploadDate: "2025-01-04",
    updateDate: "2025-01-04",
    penyuluh: "Aaron Collins",
},
{
    id: 8,
    topik: "Penyuluhan Sorgum",
    fileName: "Penyuluhan Sorgum",
    fileUrl: "/files/sorgum.pdf",
    uploadDate: "2025-01-04",
    updateDate: "2025-01-04",
    penyuluh: "Aaron Collins",
},
{
    id: 9,
    topik: "Penyuluhan Jati",
    fileName: "Penyuluhan Jati",
    fileUrl: "/files/jati.pdf",
    uploadDate: "2025-01-04",
    updateDate: "2025-01-04",
    penyuluh: "Bruce Rodriguez",
},
{
    id: 10,
    topik: "Sekolah Lapangan I",
    fileName: "Sekolah Lapangan I",
    fileUrl: "/files/sekolah1.pdf",
    uploadDate: "2025-01-04",
    updateDate: "2025-01-04",
    penyuluh: "Bettie Oliver",
},
];

export const kumpulanKegiatanData = [
    {
        id: 1,
        title: "Sekolah Lapangan I",
        address: "123 Main St, Anytown, USA",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 2,
        title: "Penyuluhan Cabai",
        address: "123 Main St, Anytown, USA",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 3,
        title: "Penyuluhan Tomat",
        address: "123 Main St, Anytown, USA",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 4,
        title: "Sekolah Lapangan II",
        address: "123 Main St, Anytown, USA",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 5,
        title: "Penyuluhan Jagung",
        address: "123 Main St, Anytown, USA",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 6,
        title: "Penyuluhan Jati",
        address: "123 Main St, Anytown, USA",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 7,
        title: "Penyuluhan Irigasi",
        address: "123 Main St, Anytown, USA",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 8,
        title: "Sekolah Lapangan III",
        address: "123 Main St, Anytown, USA",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 9,
        title: "Penyuluhan Pupuk NPK",
        address: "123 Main St, Anytown, USA",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
    {
        id: 10,
        title: "Sekolah Lapangan IV",
        address: "123 Main St, Anytown, USA",
        date: "2025-01-01",
        startTime: "10:00",
        endTime: "11:00",
    },
];

export const kumpulanDokumentasiAcaraData = [
    {
        id: 1,
        title: "Sekolah Lapangan I - Padi",
        penyuluh: "John Doe",
        photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
        description: "Penyuluhan mengenai teknik penanaman padi yang efektif dan pengendalian hama.",
        date: "2025-06-10",
    },
    {
        id: 2,
        title: "Penyuluhan Tomat",
        penyuluh: "Jane Doe",
        photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
        description: "Penyuluhan tentang cara bertanam tomat yang baik serta cara mengatasi penyakit pada tanaman tomat.",
        date: "2025-06-15",
    },
    {
        id: 3,
        title: "Sekolah Lapangan II - Jagung",
        penyuluh: "Mike Geller",
        photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
        description: "Pelatihan teknik penanaman jagung yang lebih produktif dan pengelolaan sumber daya air.",
        date: "2025-06-20",
    },
    {
        id: 4,
        title: "Penyuluhan Irigasi",
        penyuluh: "Jay French",
        photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
        description: "Pembelajaran tentang cara mengatur sistem irigasi yang efisien untuk pertanian.",
        date: "2025-06-25",
    },
    {
        id: 5,
        title: "Penyuluhan Pupuk NPK",
        penyuluh: "Jane Smith",
        photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
        description: "Cara memilih dan menggunakan pupuk NPK dengan benar untuk meningkatkan hasil pertanian.",
        date: "2025-06-30",
    },
    {
        id: 6,
        title: "Sekolah Lapangan III - Padi",
        penyuluh: "Anna Santiago",
        photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
        description: "Sekolah lapangan untuk mendalami lebih dalam mengenai teknik penanaman padi secara organik.",
        date: "2025-07-05",
    },
    {
        id: 7,
        title: "Sekolah Lapangan IV - Jagung",
        penyuluh: "Allen Black",
        photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
        description: "Sekolah lapangan mengenai teknik penanaman jagung dengan varietas unggul dan perawatan tanaman.",
        date: "2025-07-10",
    },
    {
        id: 8,
        title: "Penyuluhan Tanaman Hias",
        penyuluh: "Ophelia Castro",
        photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
        description: "Penyuluhan mengenai budidaya tanaman hias yang menguntungkan.",
        date: "2025-07-15",
    },
    {
        id: 9,
        title: "Sekolah Lapangan V - Padi",
        penyuluh: "Derek Briggs",
        photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
        description: "Sekolah lapangan mengenai teknik pertanian padi berbasis teknologi dan ramah lingkungan.",
        date: "2025-07-20",
    },
    {
        id: 10,
        title: "Penyuluhan Irigasi Tani",
        penyuluh: "John Glover",
        photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
        description: "Penyuluhan tentang pentingnya sistem irigasi yang baik untuk pertanian yang berkelanjutan.",
        date: "2025-07-25",
    },
];

export const kumpulanPengumumanData = [
    {
        id: 1,
        title: "Sekolah Lapangan I",
        parakelompoktani: ["Kelompok Tani Gemar","..."],
        date: "2025-01-01",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 2,
        title: "Penyuluhan Cabai",
        parakelompoktani: ["Kelompok Tani Sukamaju", "..."],
        date: "2025-01-01",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 3,
        title: "Penyuluhan Tomat",
        parakelompoktani: ["Kelompok Tani Oke", "..."],
        date: "2025-01-01",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 4,
        title: "Sekolah Lapangan II",
        parakelompoktani: ["Kelompok Tani Bersama", "..."],
        date: "2025-01-01",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 5,
        title: "Penyuluhan Jagung",
        parakelompoktani: ["Kelompok Tani Lestari", "..."],
        date: "2025-01-01",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 6,
        title: "Penyuluhan Jati",
        parakelompoktani: ["Kelompok Tani Gas", "..."],
        date: "2025-01-01",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 7,
        title: "Penyuluhan Irigasi",
        parakelompoktani: ["Kelompok Tani Maju", "..."],
        date: "2025-01-01",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 8,
        title: "Sekolah Lapangan III",
        parakelompoktani: ["Kelompok Tani Kembang", "..."],
        date: "2025-01-01",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 9,
        title: "Penyuluhan Pupuk NPK",
        parakelompoktani: ["Kelompok Tani Lestari", "..."],
        date: "2025-01-01",
        address: "123 Main St, Anytown, USA",
    },
    {
        id: 10,
        title: "Sekolah Lapangan IV",
        parakelompoktani: ["Kelompok Tani Lestari", "..."],
        date: "2025-01-01",
        address: "123 Main St, Anytown, USA",
    },
];

// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
    {
        title: "Sekolah",
        allDay: false,
        start: new Date(2025, 6, 4, 8, 0),
        end: new Date(2025, 6, 4, 8, 45),
    },
    {
        title: "Penyuluhan Cabai",
        allDay: false,
        start: new Date(2025, 6, 4, 9, 0),
        end: new Date(2025, 6, 4, 9, 45),
    },
    {
        title: "Penyuluhan Tomat",
        allDay: false,
        start: new Date(2025, 5, 23, 10, 0),
        end: new Date(2025, 5, 23, 10, 45),
    },
    {
        title: "Sekolah Lapangan II",
        allDay: false,
        start: new Date(2025, 5, 24, 11, 0),
        end: new Date(2025, 5, 24, 11, 45),
    },
    {
        title: "Penyuluhan Jagung",
        allDay: false,
        start: new Date(2025, 5, 19, 13, 0),
        end: new Date(2025, 5, 19, 13, 45),
    },
    {
        title: "Penyuluhan Jati",
        allDay: false,
        start: new Date(2025, 5, 19, 14, 0),
        end: new Date(2025, 5, 19, 14, 45),
    },
    {
        title: "Penyuluhan Irigasi",
        allDay: false,
        start: new Date(2025, 7, 13, 9, 0),
        end: new Date(2025, 7, 13, 9, 45),
    },
    {
        title: "Sekolah Lapangan III",
        allDay: false,
        start: new Date(2025, 7, 13, 10, 0),
        end: new Date(2025, 7, 13, 10, 45),
    },
    {
        title: "Physics",
        allDay: false,
        start: new Date(2025, 7, 13, 11, 0),
        end: new Date(2025, 7, 13, 11, 45),
    },

    {
        title: "Penyuluhan Pupuk NPK",
        allDay: false,
        start: new Date(2025, 7, 13, 14, 0),
        end: new Date(2025, 7, 13, 14, 45),
    },
    {
        title: "Sekolah Lapangan IV",
        allDay: false,
        start: new Date(2025, 7, 14, 8, 0),
        end: new Date(2025, 7, 14, 8, 45),
    },
    {
        title: "Sekolah Lapangan I",
        allDay: false,
        start: new Date(2025, 7, 14, 10, 0),
        end: new Date(2025, 7, 14, 10, 45),
    },

    {
        title: "Penyuluhan Cabai",
        allDay: false,
        start: new Date(2025, 7, 14, 13, 0),
        end: new Date(2025, 7, 14, 13, 45),
    },
    {
        title: "Penyuluhan Tomat",
        allDay: false,
        start: new Date(2025, 7, 14, 14, 0),
        end: new Date(2025, 7, 13, 14, 45),
    },
    {
        title: "Sekolah Lapangan II",
        allDay: false,
        start: new Date(2025, 7, 15, 9, 0),
        end: new Date(2025, 7, 15, 9, 45),
    },
    {
        title: "Penyuluhan Jagung",
        allDay: false,
        start: new Date(2025, 7, 15, 10, 0),
        end: new Date(2025, 7, 15, 10, 45),
    },
    {
        title: "Penyuluhan Jati",
        allDay: false,
        start: new Date(2025, 7, 15, 11, 0),
        end: new Date(2025, 7, 15, 11, 45),
    },
    {
        title: "Penyuluhan Irigasi",
        allDay: false,
        start: new Date(2025, 7, 15, 14, 0),
        end: new Date(2025, 7, 15, 14, 45),
    },
    {
        title: "Sekolah Lapangan III",
        allDay: false,
        start: new Date(2025, 7, 16, 8, 0),
        end: new Date(2025, 7, 16, 8, 45),
    },
    {
        title: "Penyuluhan Pupuk NPK",
        allDay: false,
        start: new Date(2025, 7, 16, 9, 0),
        end: new Date(2025, 7, 16, 9, 45),
    },

    {
        title: "Sekolah Lapangan IV",
        allDay: false,
        start: new Date(2025, 7, 16, 11, 0),
        end: new Date(2025, 7, 16, 11, 45),
    }
];